UDC leakage current detection implementation for fac-dcdc and ema
cnpem-sei/udc-arm-fw pull request #19
Opened 2023-01-25 12:25 UTC by RASC186

2023-01-25 12:38 UTC, gabrielbrunheira commented
There are two *.bak files (probably backup files from WinMerge usage) that shouldn't be commited. Actually, *.bak files should be in .gitignore, as they are in [udc-dsp-fw ](https://github.com/cnpem-sei/udc-dsp-fw). I suggest to delete these two files and include *.bak in .gitignore.

2023-01-25 15:04 UTC, rogeriomarcondeli approved these changes

2023-01-26 11:12 UTC, gabrielbrunheira approved these changes

2023-02-03 18:09 UTC, rogeriomarcondeli reviewed
@RASC186 Could you check the changes made

2023-02-07 20:17 UTC, gabrielbrunheira requested changes

2023-02-08 19:49 UTC, rogeriomarcondeli commented on app/communication_drivers/ps_modules/fac_dcdc/fac_dcdc.c
> -    create_bsmp_var(48, 0, 4, false, iib_fac_os.GroundLeakage.u8);
removed it from the typedef'd struct iib_fac_os_t (iib_data.h) GroundLeakage

2023-02-09 15:54 UTC, gabrielbrunheira approved these changes

2023-02-14 11:05 UTC, merged